apiVersion: v1
kind: Service
metadata:
  name: consul-ui-svc
spec:
  type: NodePort
  selector:
    app: consul
    component: server
    release: consul
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30000
      